# Generated by Django 5.2.4 on 2025-07-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SUIT', 'Suit'), ('ROBE', 'Robe'), ('TUX', 'Tuxedo'), ('GOWN', 'Gown'), ('OTHER', 'Other')], max_length=10)),
                ('image', models.ImageField(upload_to='clothing_images/')),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='models_3d/')),
            ],
        ),
    ]
